- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.8

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
    language_version: python3.8
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: requirements-txt-fixer
  - id: flake8
    language_version: python3.8
    args: [--max-line-length=88]
