version: '3'

services:
  appetiser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5080:80"
    env_file:
      - .env
    volumes:
      - $HOME\Docker\scratch\appetiser:/scratch
      #- $HOME\.aws:/root/.aws
    # entrypoint: /opt/appetiser/run_tests.sh
