services:
  appetiser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./local_data/kdu_src:/kdu_src
      - ./local_data/test_source_dir:/test_source_dir
      - ~\.aws:/root/.aws
      # - .:/opt/appetiser
